# Generated by Django 2.2.2 on 2019-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='data',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
